version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "49011:80"
    volumes:
      - .:/var/www/kp
      - ./docker/nginx/hosts:/etc/nginx/conf.d
      - ./docker/nginx/logs:/var/log/nginx
    restart: always
    links:
      - php

  php:
    build: docker/php
    volumes:
      - .:/var/www/kp
    restart: always
